name: manage-azure-policy-865e5456
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/ストレージ_アカウントではネットワーク_アクセスを制限する必要があります_34c877ad-507e-4c82-993e-3452a6e0ad3c/**'
#      - .github/workflows/manage-azure-policy-865e5456.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_865e5456}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/ストレージ_アカウントではネットワーク_アクセスを制限する必要があります_34c877ad-507e-4c82-993e-3452a6e0ad3c/**
